sudo: false

jdk:
  - oraclejdk8

language: scala

scala:
   - 2.12.1

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
   - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3db13000510c10a6698e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
